SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `biobank_specimen_attribute`;
LOCK TABLES `biobank_specimen_attribute` WRITE;
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (1,'Clotted',1,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (2,'Tube Expired',1,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (3,'Centrifuge Start #1',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (4,'Centrifuge End #1',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (5,'Centrifuge Start #2',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (6,'Centrifuge End #2',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (7,'Centrifuge Start #3',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (8,'Centrifuge End #3',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (9,'Centrifuge Start #4',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (10,'Centrifuge End #4',5,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (11,'Red Pellet',1,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (12,'Total PBMC Count (10⁶ cells)',2,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (13,'Milky Serum',1,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (14,'Hemolyzed',1,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (15,'Hemodialysis Index',2,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (16,'No Visible Pellet',1,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (17,'DNA Concentration (ng/µL)',2,NULL);
INSERT INTO `biobank_specimen_attribute` (`SpecimenAttributeID`, `Label`, `DatatypeID`, `ReferenceTableID`) VALUES (18,'260/280 Ratio',2,NULL);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
