SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `biobank_specimen_protocol_attribute_rel`;
LOCK TABLES `biobank_specimen_protocol_attribute_rel` WRITE;
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (3,11,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (3,16,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (3,17,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (3,18,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (6,1,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (6,11,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (6,12,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (7,13,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (7,14,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (7,15,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,1,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,2,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,3,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,4,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,5,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,6,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,7,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (8,8,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (9,2,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (9,3,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (9,4,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,2,_binary '\0');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,3,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,4,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,5,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,6,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,7,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,8,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,9,_binary '');
INSERT INTO `biobank_specimen_protocol_attribute_rel` (`SpecimenProtocolID`, `SpecimenAttributeID`, `Required`) VALUES (10,10,_binary '');
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
