SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE `biobank_specimen`;
LOCK TABLES `biobank_specimen` WRITE;
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (1,1,7,10.000,2,1053);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (2,2,6,40.000,1,2148);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (3,3,1,8.000,3,1347);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (4,4,1,10.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (5,5,1,10.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (6,6,1,10.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (7,7,1,10.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (8,8,1,0.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (9,9,1,0.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (10,10,1,0.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (11,11,1,0.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (12,12,1,0.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (13,13,1,0.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (14,14,1,0.000,3,2162);
INSERT INTO `biobank_specimen` (`SpecimenID`, `ContainerID`, `SpecimenTypeID`, `Quantity`, `UnitID`, `SessionID`) VALUES (15,15,7,5.000,2,2162);
UNLOCK TABLES;
SET FOREIGN_KEY_CHECKS=1;
